Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Neos.Form.AltchaCaptcha: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.Form.AltchaCaptcha:
            - 'Captcha'
  Form:
    presets:
      default:
        formElementTypes:
          'NeosRulez.Neos.Form.AltchaCaptcha:Captcha':
            renderingOptions:
              templatePathPattern: 'resource://NeosRulez.Neos.Form.AltchaCaptcha/Private/Templates/Form/{@type}.html'
            superTypes:
              'Neos.Form:FormElement': true
            properties:
              elementClassAttribute: form-control
              elementErrorClassAttribute: is-invalid
        validatorPresets:
          'NeosRulez.Neos.Form.AltchaCaptcha:Validator':
            implementationClassName: NeosRulez\Neos\Form\AltchaCaptcha\Validation\Captcha\CaptchaValidator
      bootstrap:
        formElementTypes:
          'NeosRulez.Neos.Form.AltchaCaptcha:Captcha':
            renderingOptions:
              templatePathPattern: 'resource://NeosRulez.Neos.Form.AltchaCaptcha/Private/Templates/Form/{@type}.html'
            superTypes:
              'Neos.Form:FormElement': true
            properties:
              elementClassAttribute: form-control
              elementErrorClassAttribute: is-invalid
        validatorPresets:
          'NeosRulez.Neos.Form.AltchaCaptcha:Validator':
            implementationClassName: NeosRulez\Neos\Form\AltchaCaptcha\Validation\Captcha\CaptchaValidator

NeosRulez:
  Neos:
    Form:
      AltchaCaptcha:
        view:
          hideAltchaLogo: false
          hideFooter: false
          auto: false
        security:
          minNumber: 5000
          maxNumber: 15000
          hmac: 1742225261
          expires: 1200
