Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Neos.Form.AltchaCaptcha: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.Form.AltchaCaptcha:
            - 'Captcha'
  Form:
    presets:
      default:
        formElementTypes:
          'NeosRulez.Neos.Form.AltchaCaptcha:Captcha':
            renderingOptions:
              templatePathPattern: 'resource://NeosRulez.Neos.Form.AltchaCaptcha/Private/Templates/Form/{@type}.html'
            superTypes:
              'Neos.Form:FormElement': true
            properties:
              elementClassAttribute: form-control
              elementErrorClassAttribute: is-invalid
        validatorPresets:
          'NeosRulez.Neos.Form.AltchaCaptcha:Validator':
            implementationClassName: NeosRulez\Neos\Form\AltchaCaptcha\Validation\Captcha\CaptchaValidator
      bootstrap:
        formElementTypes:
          'NeosRulez.Neos.Form.AltchaCaptcha:Captcha':
            renderingOptions:
              templatePathPattern: 'resource://NeosRulez.Neos.Form.AltchaCaptcha/Private/Templates/Form/{@type}.html'
            superTypes:
              'Neos.Form:FormElement': true
            properties:
              elementClassAttribute: form-control
              elementErrorClassAttribute: is-invalid
        validatorPresets:
          'NeosRulez.Neos.Form.AltchaCaptcha:Validator':
            implementationClassName: NeosRulez\Neos\Form\AltchaCaptcha\Validation\Captcha\CaptchaValidator

  Fusion:
    defaultContext:
      Altcha: 'NeosRulez\Neos\Form\AltchaCaptcha\Eel\Helper\AltchaHelper'

#NeosRulez:
#  Neos:
#    Form:
#      AltchaCaptcha:
#        view:
#          hideAltchaLogo: false
#          hideFooter: false
#          auto: disabled
#        security:
#          minNumber: 5000
#          maxNumber: 15000
#          hmac: 3f4bb586f04a0c1d93eadab9363a8a3183b4860c
#          expires: 1200
